### ISSUE TITLE
Client does not load (Only a blank screen is displayed)

### ISSUE THREAD

**Issue by hcuffy** [freeCodeCamp/league-for-good#111]
To reproduce:
 - Fork and download the repo
 - Setup up environment as for README
 - Subdue errors associated with: https://github.com/freeCodeCamp/league-for-good/issues/104
 - Run npm run dev

Result: A blank screen is displayed.

- Check the console the following will be displayed:
`Uncaught TypeError: Cannot read property 'injection' of undefined
    at e.exports (injectTapEventPlugin.js:23)
    at Object.<anonymous> (app.jsx:24)
    at n (bootstrap:19)
    at Object.<anonymous> (index.js:9)
    at n (bootstrap:19)
    at bootstrap:83
    at bootstrap:83`

Confirmed on
OSX
Chrome : Version 68.0.3440.106 (Official Build) (64-bit)
Firefox : 62.0 (64-bit

<img width="1330" alt="screen shot 2018-09-09 at 5 51 42 pm" src="https://user-images.githubusercontent.com/11555955/45266284-1871cb80-b459-11e8-8657-787f4acffc6d.png">

**Comment by lieberscott** [comment]
This is because the onTouchTap event is deprecated, and so the React Tap Event Plugin code no longer works with the latest version of React. I have a pull request to remove this code from the app and to change the deprecated onTouchTap events that are scattered throughout the app to onClick.

My pull request is here: https://github.com/freeCodeCamp/league-for-good/pull/109

Since my PR hasn't been accepted yet, you can manually comment it out in the app.jsx file to get it working. You'll then notice there's very little functionality because onTouchTap is deprecated, and if you'd like you can manually change any onTouchTap with onClick to get the functionality of the app back.

**Comment by hcuffy** [comment]
@lieberscott The issue has been fixed 👍.--Closing issue.
